### ISSUE TITLE
PlusROM header being read from wrong offset in ROM?

### ISSUE THREAD

**Issue by brpocock** [JetSetIlly/Gopher2600#35] opened 2024-12-13 15:26 UTC
The PlusCart firmware, and Stella, use a rather strange mechanism for finding the PlusROM path & host strings:

The address in NMIVEC is taken to be a ROM-relative offset + $1000

https://github.com/Al-Nafuur/United-Carts-of-Atari/blob/b1ed2d6b43c1af9ac349af7652c78ee74dd16861/source/STM32firmware/PlusCart/Src/cartridge_detection.c#L60

```
	uint16_t * nmi_p = (uint16_t * )&bytes[size - 6];
	int i = nmi_p[0] - 0x1000 , hostHasNoDot = 1;
```

https://github.com/stella-emu/stella/blob/617147a175d5783f9820098023c63625ecbf88fc/src/emucore/PlusROM.cxx#L212

```
  // Host and path are stored at the NMI vector
  size_t i = ((image[size - 5] - 16) << 8) | image[size - 6];  // NMI @ $FFFA
```

So e.g. if the ROM uses 1k banks (3E+ in this case) and the address is $2020, then the strings should be located at $1020 into the ROM file, which is a.k.a. Bank 4 offset $0020.

Unfortunately, the Gopher2600 emulation does something different, meaning that the URL strings must be recorded in multiple banks to support both PlusCart/Stella and Gopher2600.

https://github.com/JetSetIlly/Gopher2600/blob/11848209d07d39a2c1c3e8abf8431358ea037008/hardware/memory/cartridge/plusrom/plusrom.go#L75C1-L90C30

```
	// host/path information is found at address 0x1ffa. we've got a reference
	// to the last bank above but we need to consider that the last bank might not
	// take the entirity of the cartridge map.
	addrMask := uint16(len(lastBank.Data) - 1)

	// host/path information are found at the address pointed to by the following
	// 16bit address
	const addrinfoMSB = 0x1ffb
	const addrinfoLSB = 0x1ffa

	a := uint16(lastBank.Data[addrinfoLSB&addrMask])
	a |= (uint16(lastBank.Data[addrinfoMSB&addrMask]) << 8)

	// get bank to which the NMI vector points
	b := int((a & 0xf000) >> 12)
```

This seems to make the encoding rather (bank * $1000 + offset), so $2020 is interpreted as bank $2, offset $020, which is entirely different.

**Comment by JetSetIlly** [comment] 2024-12-13 18:23
Hi Bruce,

Thanks for the bug report. I understand what the issue is. 

Before I push the changes that fix the problem, do you have an example of a ROM that doesn't currently work in Gopher2600 so I can test that it works.

**Comment by brpocock** [comment] 2024-12-13 19:39
I "fixed" mine by duplicating the strings but I'll send shortly a version without that "fix" in place

**Comment by brpocock** [comment] 2024-12-13 19:46
![image](https://github.com/user-attachments/assets/a9c2fe02-9a43-4527-b205-b7915efa0087)
![image](https://github.com/user-attachments/assets/f71e4e88-c443-4855-9bf3-bcf732be997a)

Here's a (very) minimal one that should ping a 4-byte "HELO" to the PlusROM server at http://delving.interworldly.com/plus and then display flashing colors with PF2 black bars over them.

![Screenshot From 2024-12-13 09-26-14](https://github.com/user-attachments/assets/de576009-d963-4e1b-a92c-be169c4fff06)

**Comment by JetSetIlly** [comment] 2024-12-13 19:53
Thanks. That seems to work.

I've pushed a fix to the `maintenance_work_0.35.2` branch. Are you setup to compile your own binaries?

If not, I can make another binary release later this weekend

**Comment by brpocock** [comment] 2024-12-13 20:35
I have not tried, yet, but I'll see if I can!

**Comment by brpocock** [comment] 2024-12-13 20:40
It seems you may require a newer version of Go than I have readily available
```
go: errors parsing go.mod:
/home/brpocock/Projects/Gopher2600/go.mod:3: invalid go version '1.22.0': must match format 1.23
```

```
⇒ go version
go version go1.18 gccgo (GCC) 14.2.1 20240912 (Red Hat 14.2.1-3) linux/amd64

```

I'd appreciate a build at your convenience, but no rush of course!

**Comment by JetSetIlly** [comment] 2024-12-14 09:30
Binaries in new release https://github.com/JetSetIlly/Gopher2600/releases/tag/v0.35.3

**Closed** 2024-12-16 17:06 UTC
